PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS positions;
CREATE TABLE positions (position_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, position VARCHAR (20) NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;